#########################################################################
# ⭐⭐⭐  Set parameters carefully for satisfied performance!   ⭐⭐⭐ #
#########################################################################

mass: 1.5 # kg
gra: 9.81
pose_solver: 1 # 0:From ZhepeiWang (drag & less singular) 1:From ZhepeiWang, 2:From rotor-drag
ctrl_freq_max: 30.0
use_bodyrate_ctrl: false
max_manual_vel: 5.0
max_manual_vel_z: 1.0
max_angle: 30 # Attitude angle limit in degree. A negative value means no limit.
low_voltage: 13.2 # 4S battery

use_global_odom: false
no_odom: false
rc_reverse: # *
    roll: false
    pitch: false
    yaw: false
    throttle: false

rc_channal:
    gear_channal: 5

auto_takeoff_land:
    enable: true
    no_RC: false
    takeoff_height: 1.5 # m
    takeoff_land_speed: 1.0 # m/s

thrust_model: # The model that maps thrust signal u(0~1) to real thrust force F(Unit:N): F=K1*Voltage^K2*(K3*u^2+(1-K3)*u).
    update: false
    print_value: false # display the value of “thr_scale_compensate” or “hover_percentage” during thrust model estimating.
    accurate_thrust_model: false # This can always enabled if don't require accurate control performance :-)
    # accurate thrust mapping parameters
    K1: 0.7583 # Needs precise calibration!
    K2: 1.6942 # Needs precise calibration!
    K3: 0.6786 # Needs precise calibration! K3 equals THR_MDL_FAC in https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html.
    # approximate thrust mapping parameters
    hover_percentage: 0.30 # Thrust percentage in Stabilize/Arco mode # *

rotor_drag:
    x: 0.0 # The reduced acceleration on each axis caused by rotor drag. Unit:(m*s^-2)/(m*s^-1).
    y: 0.0 # Same as above
    z: 0.0 # Same as above
    k_thrust_horz: 0.0 # Set to 0 recommended... --

msg_timeout:
    odom: 0.5
    rc: 0.5
    cmd: 0.5
    imu: 0.5
    bat: 0.5
    vfr: 0.5
    slow_down: 0.5
geo_controller:
    velocity_yaw: false # Cal Yaw Based on the Velocity Direction.
    drag_dx: 0.0
    drag_dy: 0.0
    drag_dz: 0.0
    Kpos_x_: 6.0
    Kpos_y_: 6.0
    Kpos_z_: 8.5
    Kvel_x_: 3.5
    Kvel_y_: 3.5
    Kvel_z_: 5.5
    attctrl_tau_: 0.5
    max_fb_acc_: 20.0

topics_record_list:
    - /bfctrl/cmd
    - /bfctrl/des
    - /bfctrl/home_pose
    - /bfctrl/local_odom
    - /bfctrl/statue
    - /bfctrl/takeoff_land
    - /airsim_node/drone_1/front_center/DepthPlanar
